config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/search' => 'search#index'

  resources :subscriptions
  resources :items, only: [:new, :create]

  resources :stories, only: [] do
    member do
      post :read
    end
  end

  root to: redirect('/search')
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  include Taggable

  belongs_to :user
  belongs_to :feed

  validates :feed_id,
            presence: true,
            uniqueness: { scope: :user_id }

  delegate :title,   to: :feed
  delegate :url,     to: :feed
  delegate :favicon, to: :feed
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController

  def index
    @subscriptions = current_user.subscriptions.includes(:feed)
  end

  def new
    @subscription = current_user.subscriptions.new(feed: Feed.new)
  end

  def edit
    @subscription = current_user.subscriptions.find(params[:id])
    render :new
  end

  def create
    data = subscription_params
    feed = Feed.where(url: data.delete(:url)).first_or_create
    @subscription = current_user.subscriptions.create(data.merge(feed: feed))

    if @subscription.persisted?
      RefreshFeedWorker.perform_async(feed.id)
    end

    respond_with @subscription, location: -> { subscriptions_path }
  end

  def update
    data = subscription_params
    data.delete(:url)

    @subscription = current_user.subscriptions.find(params[:id])
    @subscription.update(subscription_params)
    SyncSubscriptionWorker.perform_async(@subscription.id)

    respond_with @subscription, location: -> { subscriptions_path }
  end

  def destroy
    @subscription = current_user.subscriptions.find(params[:id])
    @subscription.destroy

    redirect_to subscriptions_path
  end

  private

  def subscription_params
    params.require(:subscription).permit(:url, :tags)
  end
end

app/views/subscriptions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <main role="main" class="subscriptions col-md-9 ml-sm-auto col-lg-12">
      <% if @subscriptions.length > 0 %>
        <div class="list-group subscriptions">
          <% @subscriptions.each do |subscription| %>
            <%= link_to edit_subscription_url(subscription),
              class: "list-group-item list-group-item-action d-flex #{subscription.feed.error? ? "list-group-item-danger" : ""}" do %>
              <div>
                <span><%= feed_favicon(subscription.feed) %></span>
                <span><%= feed_title(subscription.feed) %></span>
              </div>

              <div class="ml-auto">
                <% subscription.tags.each do |tag| %>
                  <span class="badge badge-secondary"><%= tag %></span>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>

      <% else %>
        <div class="text-center inbox-zero">
          <h2>No Subscriptions Found!</h2>
        </div>
      <% end %>
    </main>
  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="container-fluid">
  <div class="row">
    <main role="main" class="col-md-12 ml-sm-auto">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><%= @subscription.persisted? ? "Edit subscription" : "Create a new subscription" %></h1>
      </div>

      <%- if @subscription.feed.error? -%>
        <div class="alert alert-danger" role="alert"><%= @subscription.feed.error %></div>
      <%- end -%>

      <%= form_for @subscription do |f| %>
        <div class="form-row">
          <div class="form-group col-md-11">
            <% if @subscription.persisted? %>
              <div class="form-control"><%= @subscription.url %></div>
            <% else %>
              <%= f.text_field :url, class: "form-control", placeholder: "URL" %>
            <% end %>
          </div>
          <div class="form-group col-md-11">
            <%= f.text_field :tags, class: "form-control", placeholder: "Comma-separated tags" %>
          </div>
          <div class="form-group col-md-11">
            <%= f.submit @subscription.persisted? ? "Update" : "Create", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>

      <% if @subscription.persisted? %>
        <div class="alert alert-warning">
          <h4 class="alert-heading">Destroy subscription</h4>
          <p>After destroying a subscription, you will stop receiving new items from that feed. Any existing item will remain searchable.</p>
          <hr />

          <p class="mb-0">
            <%= link_to 'Destroy', @subscription, method: :delete, class: 'btn btn-warning' %>
          </p>
        </div>
      <% end %>
    </main>
  </div>
</div>