config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/search' => 'search#index'

  resources :subscriptions
  resources :items, only: [:new, :create]

  resources :stories, only: [] do
    member do
      post :read
    end
  end

  root to: redirect('/search')
end

app/controllers/application_controller.rb
# frozen_string_literal: true

require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json
  before_action :verify_requested_format!

  before_action :authenticate_user!, :set_raven_context

  private

  def authenticate_user!
    if !user_signed_in?
      redirect_to user_github_omniauth_authorize_path
    end
  end

  def set_raven_context
    Raven.user_context(id: current_user.id) if user_signed_in?
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to "Newsroom", root_path, class: "navbar-brand" %>
    <%= form_tag('/search', class: 'w-100', method: :get) do %>
      <%= text_field_tag 'q', params[:q], class: 'form-control form-control-dark w-100', placeholder: "Search" %>
    <% end %>
  </nav>
</header>

app/views/application/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to root_url, class: "nav-link" do %>
          <i class="fe fe-home"></i>
          Inbox
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_item_url, class: "nav-link" do %>
          <i class="fe fe-plus"></i>
          New Item
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_subscription_url, class: "nav-link" do %>
          <i class="fe fe-plus"></i>
          New Subscription
        <% end %>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">Tags</h6>
    <ul class="nav flex-column mb-2">
      <% @tags.each do |tag| %>
        <li class="nav-item">
          <%= link_to search_path(q: "tag:#{tag}"), class: "nav-link" do %>
            <i class="fe fe-hash"></i>
            <%= tag %>
          <% end %>
        </li>
      <% end %>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">Settings</h6>

    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to subscriptions_url, class: "nav-link" do %>
          <i class="fe fe-wrench"></i>
          Manage Subscriptions
        <% end %>
      </li>
    </ul>

  </div>
</nav>